name: parenthesis_matching_dart
description: Dart implementation of parenthesis matching problem.
# version: 1.0.0
# author: João Vicente <joaovic@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
